service: serverless-django-ecom

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: Ecom.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux
    zip : true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  iam.role.statements:
    - Effect: "Allow"
      Action:
       - s3:GetObject
       - s3:PutObject
      Resource: "arn:aws:s3:::*"

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

package:
  exclude:
    - node_modules/**
    - myenv/**
