# Generated by Django 3.0.14 on 2022-04-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
